# Generated by Django 3.0.2 on 2020-02-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200204_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descrippythotion',
            new_name='description',
        ),
    ]
